#!/bin/sh                                                                                       

PID="org.webosinternals.precorder"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

MP3LAME="bin/libmp3lame.so"
GSTLAME="bin/libgstlame.so"
GSTLEVEL="bin/libgstlevel.so"
MP3LAMESYM1="/usr/lib/libmp3lame.so"
MP3LAMESYM2="/usr/lib/libmp3lame.so.0"
GSTLAMESYM="/usr/lib/gstreamer-0.10/libgstlame-webosinternals.so"
GSTLEVELSYM="/usr/lib/gstreamer-0.10/libgstlevel-webosinternals.so"

# Symlink lame binary
rm -f $MP3LAMESYM1
rm -f $MP3LAMESYM2
ln -s $IPKG_OFFLINE_ROOT/usr/palm/applications/$PID/$MP3LAME $MP3LAMESYM1
ln -s $MP3LAMESYM1 $MP3LAMESYM2

# Symlink gstreamer binaries
rm -f $GSTLAMESYM
rm -f $GSTLEVELSYM
ln -s $IPKG_OFFLINE_ROOT/usr/palm/applications/$PID/$GSTLAME $GSTLAMESYM
ln -s $IPKG_OFFLINE_ROOT/usr/palm/applications/$PID/$GSTLEVEL $GSTLEVELSYM

# Register gstreamer binaries
gst-inspect > /dev/null

# Stop any existing service
/sbin/stop ${PID} || true

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}

# Copy executable outside of encrypted mount
mkdir -p /var/usr/sbin/
rm -f /var/usr/sbin/${PID}
install -m 755 $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/bin/${PID} /var/usr/sbin/${PID}

# Start the service
/sbin/start ${PID}

exit 0
